### PR TITLE
Add interface IOpenLibraryClient

### PR DESCRIPTION
**Pull request by Luca3317**

### CODE REVIEW

**Comment by JeCFe** [comment]
Was unable to commit anything to this PR, have forked the repo and issues a  [new PR](https://github.com/Luca3317/OpenLibrary.NET/pull/13)

**Comment by bradyguyc** [comment]
@JeCFe could you take a look at issue 12 , https://github.com/Luca3317/OpenLibrary.NET/issues/12
And see if you could add a test for this issue?  Or maybe provide me a little instruction on how to do it with your process?

**Comment by JeCFe** [comment]
I'll take a look at the issue, and see if I can suggest a reasonable path. 
From an initial glance, it appears you could use `Moq` to mock out the underline HttpMessageHandler implementation that is passable into HTTPClient. 

It gets a bit funky as the `SendAsync` method on the HTTPMessageHandler is a protect method, but I believe `Moq` has a way to handle mocking protected methods. 

I can take a lot and hopefully be able to provide you a way to mock the required parts. 

However, anytime you're mocking raw HTTP implementation means there's usually a better approach. A better alternative (but a relatively substantial refactor) would be to rely on dotnet [dependancy injection patterns](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0), in which case you would be able to mock out the interface for the necessary methods. Ideally you'd put anything that touches raw HTTP into a class with interface, and then have this dependancy injected where it gets used

**Comment by JeCFe** [comment]
@bradyguyc  I've add an example for how you can mock the HTTP client on #12 

Edit: Tagged wrong person

**Pull request closed without merging**
